version: '3.8'

services:
  auction-service:
    image: cbjoedstrup/auctionservicetest-image:1.1.1
    container_name: auctionservice
    ports:
      - "5004:8080"
    environment:
      - RabbitHost=rabbitmq  # Miljøvariabel for RabbitMQ
      - AUTHSERVICE_URL=http://authservice:8080
    networks:
      - hemmelig-env_auctionGOnet
    healthcheck:
      test: ["CMD", "true"]  # En simpel kommando, der altid returnerer succes
      interval: 30s  # Udfør healthcheck hver 30 sekunder
      retries: 5      # Prøv op til 5 gange
      start_period: 10s  # Vent 10 sekunder før første healthcheck
      timeout: 10s    # Timeout på 10 sekunder per healthcheck
    command: /bin/sh -c "sleep 15 && dotnet bidworker.dll"  # Erstat med den kommando, der starter din applikation
    restart: on-failure

networks:
  hemmelig-env_auctionGOnet:
    external: true
